# dataset
# dataset name, param1, param2
dataset: 20newsgroups

# embeddings
embedding: glove,50
# information aggregation method to document-level representations
# avg, concat, prune-sequence
aggregation: avg

# semantic resource settings
# resource,population_strategy,weighting_strategy,pruning_strategy

semantic_resource: wordnet
# the form of semantic information to use
# frequencies or tfidf
semantic_type: freq
# how the semantic information is combined with the textual one
enrichment: concat
# pos, embedding-centroid
disambiguation: pos

# learning model
# dnn or lstm
learner: dnn

train:
  epochs: 50
  folds: 3
  early_stopping_patience: -1

batch_size: 20
#log_level: debug
log_level: info

#parallelization: 10
#parallelization: 4

options:
  data_limit: 100
#  data_limit: 100

results_folder: "results"
serialization_dir: "serialization"
embeddings_folder: "serialization"
semantic_folder: "serialization"
