# dataset
# dataset name, param1, param2
dataset: 20newsgroups

# embeddings
embedding: glove,50
# information aggregation method to document-level representations
# avg, concat, prune-sequence
aggregation: avg

# semantic resource settings
# resource,population_strategy,weighting_strategy,pruning_strategy
semantic_resource: wordnet
# how the semantic information is combined with the textual one
enrichment: concat

# learning model
# dnn or lstm
learner: dnn

train:
  epochs: 50
  folds: 3
  early_stopping_patience: -1

batch_size: 20
log_level: info


options:
  data_limit: 100

results_folder: "results"
